import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Giuseppe Mazzeo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body className='h-screen flex flex-col justify-between items-center'>
        
        <Header/>

        <main className="w-[600px] p-[30px] mt-[90px] mb-[30px] rounded-[10px] shadow-[5px_5px_6px_rgba(0,0,0,0.2)]">
          {children}
        </main>

        <Footer/>
      </body>
    </html>
  );
}
